# Generated by Django 4.0.5 on 2022-06-10 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='author_createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='administrator.administrator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authors',
            name='author_updatedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='administrator.administrator'),
            preserve_default=False,
        ),
    ]
