# Generated by Django 4.0.5 on 2022-06-11 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_phoneNumber', models.CharField(max_length=11)),
                ('user_nationalIdentificationNumber', models.CharField(max_length=12)),
                ('user_dateOfBirth', models.DateField()),
                ('user_userName', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=255)),
                ('user_permission', models.BooleanField(default=True)),
                ('user_createdAt', models.DateTimeField()),
                ('user_updatedAt', models.DateTimeField()),
                ('user_membershipStart', models.DateField()),
                ('user_membershipEnd', models.DateField()),
                ('user_createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_by', to='administrator.administrator')),
                ('user_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_by', to='administrator.administrator')),
            ],
        ),
    ]
