# Generated by Django 4.0.5 on 2022-06-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
                ('genre_description', models.TextField(max_length=1000)),
                ('genre_code', models.CharField(max_length=10)),
                ('genre_updatedAt', models.DateTimeField()),
                ('genre_createdAt', models.DateTimeField()),
            ],
        ),
    ]
