# Generated by Django 4.0.5 on 2022-06-08 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgenre_name', models.CharField(max_length=50)),
                ('subgenre_description', models.TextField(max_length=1000)),
                ('subgenre_code', models.CharField(max_length=10)),
                ('subgenre_updatedAt', models.DateTimeField()),
                ('subgenre_createdAt', models.DateTimeField()),
                ('subgenre_ofGenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.genre')),
            ],
        ),
    ]
