# Generated by Django 4.0.5 on 2022-06-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_subgenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('theme_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=50)),
                ('theme_description', models.CharField(max_length=255)),
                ('theme_createdAt', models.DateTimeField()),
                ('theme_updatedAt', models.DateTimeField()),
            ],
        ),
    ]
