# Generated by Django 4.0.5 on 2022-06-10 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('genre', '0003_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genre_created_by', to='administrator.administrator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_updatedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genre_updated_by', to='administrator.administrator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subgenre',
            name='subgenre_createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subgenre_created_by', to='administrator.administrator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subgenre',
            name='subgenre_updatedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subgenre_updated_by', to='administrator.administrator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='themes',
            name='theme_createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theme_created_by', to='administrator.administrator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='themes',
            name='theme_updatedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theme_updated_by', to='administrator.administrator'),
            preserve_default=False,
        ),
    ]
