# Generated by Django 4.0.5 on 2022-06-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator_name', models.CharField(max_length=50)),
                ('administrator_username', models.CharField(max_length=50)),
                ('administrator_password', models.CharField(max_length=255)),
                ('administrator_email', models.EmailField(max_length=50)),
                ('administrator_dateOfBirth', models.DateField()),
                ('administrator_nationalIdentificationNumber', models.CharField(max_length=12)),
                ('administrator_updatedAt', models.DateTimeField()),
                ('administrator_role', models.SmallIntegerField()),
                ('administrator_status', models.BooleanField(default=False)),
                ('administrator_createdAt', models.DateTimeField()),
                ('administrator_lastLogin', models.DateTimeField()),
            ],
        ),
    ]
