# Generated by Django 4.0.5 on 2022-06-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanStatus',
            fields=[
                ('loanStatus_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanStatus_name', models.IntegerField(max_length=50)),
                ('loanStatus_createdAt', models.DateTimeField()),
                ('loanStatus_updatedAt', models.DateTimeField()),
                ('loanStatus_createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_created_by', to='administrator.administrator')),
                ('loanStatus_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_updated_by', to='administrator.administrator')),
            ],
        ),
    ]
