# Generated by Django 4.0.5 on 2022-06-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanstatus',
            name='loanStatus_name',
            field=models.CharField(max_length=50),
        ),
    ]
